### ISSUE TITLE
서버 재시작 후, 페이지 안 열리는 문제

### ISSUE THREAD

**Issue by iykkim** [SeongSikChae/PowerManagerServer#2]
안녕하세요.

다른 문제가 있어서 문의 드립니다..

어제 밤에 서버 Shutdown 하고, 오늘 아침 Power Manager Server를 다시 시작하고 나서 관리 페이지를 열려고 하면 http 404 메세지만 나와서 server.log를 확인해 보면 다음과 같은 Error가 발생하고 있습니다.

2022-03-13 09:19:12,702 [ERROR] [Microsoft.AspNetCore.SpaServices.SpaDefaultPageMiddleware+<>c__DisplayClass0_0.<Attach>b__1:0] An unhandled exception has occurred while executing the request.
System.InvalidOperationException: The SPA default page middleware could not return the default page '/index.html' because it was not found, and no other middleware handled the request.
Your application is running in Production mode, so make sure it has been published, or that you have built your SPA manually. Alternatively you may wish to switch to the Development environment.

   at Microsoft.AspNetCore.SpaServices.SpaDefaultPageMiddleware.<>c__DisplayClass0_0.<Attach>b__1(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseExtensions.<>c__DisplayClass1_1.<Use>b__1(HttpContext context)
   at Microsoft.AspNetCore.SpaServices.SpaDefaultPageMiddleware.<>c__DisplayClass0_0.<Attach>b__0(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseExtensions.<>c__DisplayClass1_1.<Use>b__1(HttpContext context)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
   at PowerManagerServer.RequestLoggingMiddleware.Invoke(HttpContext context) in E:\Git\PowerManager\PowerManagerServer\RequestLoggingMiddleware.cs:line 36
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

PowerManager 서버 프로세스는 잘 구동 중인데, 무슨 문제인지 모르겠네요..
밤에 서버 Shutdown 그리고 오늘 아침에 서버 시작한 내용 외에 변경한 사항도 없습니다.

**Comment by iykkim** [comment]
서버 프로세스를 rorot로 스위치 후에 시작하지 않고, 메뉴얼대로 sudo ./start.sh로 시작하니까 다시 잘 됩니다.
이 내용은 닫겠습니다. ^^

**Comment by SeongSikChae** [comment]
특정한 상황에서 su root로 했을 때 내부 경로를 못찾는 문제갔긴 하지만
su root 보다 sudo 로 하는 것을 보안적으로 더 권고되는 상황이므로 별다른 조치는 하지 않도록 하겠습니다.
